### ISSUE TITLE
Plugin fails to start

### ISSUE THREAD

**Issue by nblair** [InfoSec812/nexus-kubernetes-openshift#5]
I tried deploying the jar deliverable in a NXRM 3.17 instance and got the following error in the nexus.log in the startup process:

```
2019-07-15 15:29:11,942-0500 ERROR [FelixDispatchQueue] *SYSTEM com.redhat.labs.nexus.openshift-plugin - FrameworkEvent ERROR - com.redhat.labs.nexus.openshift-plugin
org.osgi.framework.BundleException: Unable to resolve com.redhat.labs.nexus.openshift-plugin [53](R 53.0): missing requirement [com.redhat.labs.nexus.openshift-plugin [53](R 53.0)] osgi.wiring.package; (&(osgi.wiring.package=io.fabric8.kubernetes.api.model)(version>=4.3.0)) Unresolved requirements: [[com.redhat.labs.nexus.openshift-plugin [53](R 53.0)] osgi.wiring.package; (&(osgi.wiring.package=io.fabric8.kubernetes.api.model)(version>=4.3.0))]
	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4132)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2117)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1371)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
	at java.lang.Thread.run(Thread.java:748)
```

I noticed that the jar is pretty small (22Kb), it doesn't have the dependencies shaded in it. I'm no expert on OSGi or karaf, but I tried to get a kar deliverable by adding the following to the pom:

```
     <plugin>
        <groupId>org.apache.karaf.tooling</groupId>
        <artifactId>karaf-maven-plugin</artifactId>
        <executions>
          <execution>
            <goals>
              <goal>kar</goal>
            </goals>
            <phase>package</phase>
          </execution>
        </executions>
      </plugin>
```

This produces a kar file with the dependencies included:

```
~/git/nexus-kubernetes-openshift(master ✗) ls -al target/nexus-openshift-plugin-3.17.0-01.kar
-rw-r--r--  1 nblair  staff  18342019 Jul 16 08:22 target/nexus-openshift-plugin-3.17.0-01.kar
```

But that still produces a similar error during startup:

```
WARN  [fileinstall-/Users/nblair/git/nexus-internal/target/nexus-professional-3.17.0-01/deploy] *SYSTEM org.apache.karaf.kar.internal.KarServiceImpl - Unable to install Kar feature nexus-openshift-plugin/3.17.0.01
org.osgi.service.resolver.ResolutionException: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=nexus-openshift-plugin; type=karaf.feature; version="[3.17.0.01,3.17.0.01]"; filter:="(&(osgi.identity=nexus-openshift-plugin)(type=karaf.feature)(version>=3.17.0.01)(version<=3.17.0.01))" [caused by: Unable to resolve nexus-openshift-plugin/3.17.0.01: missing requirement [nexus-openshift-plugin/3.17.0.01] osgi.identity; osgi.identity=io.fabric8.openshift-client; type=osgi.bundle; version="[4.3.0,4.3.0]"; resolution:=mandatory [caused by: Unable to resolve io.fabric8.openshift-client/4.3.0: missing requirement [io.fabric8.openshift-client/4.3.0] osgi.wiring.package; filter:="(&(osgi.wiring.package=io.fabric8.kubernetes.api.builder)(version>=4.3.0)(!(version>=5.0.0)))" [caused by: Unable to resolve io.fabric8.kubernetes-model/4.3.0: missing requirement [io.fabric8.kubernetes-model/4.3.0] osgi.wiring.package; filter:="(&(osgi.wiring.package=javax.validation)(version>=2.0.0)(!(version>=3.0.0)))"]]]
	at org.apache.felix.resolver.ResolutionError.toException(ResolutionError.java:42)
	at org.apache.felix.resolver.ResolverImpl.doResolve(ResolverImpl.java:389)
	at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:375)
	at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:347)
	at org.apache.karaf.features.internal.region.SubsystemResolver.resolve(SubsystemResolver.java:216)
	at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:263)
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1176)
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl$1.call(FeaturesServiceImpl.java:1074)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

I'm not sure how to resolve bundling errors like this...

**Comment by InfoSec812** [comment]
Yep, I am completely aware. This is a brand new effort and as such is it still VERY fragile... I'm getting closer by the day... The latest tag, v0.2.0, works locally for me and in my OpenShift cluster. I cannot guarantee it will work for you . . . YET. I should have the new release up later today.

**Comment by InfoSec812** [comment]
I was just able to successfully use the 0.2.0 release on OpenShift 3.11(K8s 1.11). It should be compatible with all recent versions of Nexus and Kubernetes. The only 2 API types required are V1ConfigMap and V1Secret, so that should work with most Kubernetes distributions.

**Comment by InfoSec812** [comment]
@nblair Can you confirm this is fixed?

**Comment by nblair** [comment]
Yep, I pulled the latest from master 1d4d1b3, built the bundle and deployed to a local 3.18 instance. Bundle deployed successfully - thanks!
